name: Documentation

on:
  pull_request:
  push:
    branches: ['*.x']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-docs.yml@830e5953c0a1244b4e7a772b6e728492bdd8ef9f
    with:
      artifact-name: filament-page-header-docs
      deploy: false
