name: Code quality

on:
  push:
    branches: ['*.x']
  pull_request:

permissions:
  contents: read

concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-quality.yml@5a47fd17171530d4f969a9699d184725b7d32d44
    with:
      php-version: '8.4'
      static-analysis: true
