name: Code quality

on:
  push:
    branches: ['*.x']
  pull_request:

permissions:
  contents: read

concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-quality.yml@fd1b3f6ef3fd383de952c8a4f210c51b49f63e36
    with:
      php-version: '8.4'
      static-analysis: false
