name: Package standard

on:
  pull_request:
  push:
    branches:
      - main
      - '*.x'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: standard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standard:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-standard-check.yml@90c3c6765c2fd918755497803dfc9b8a0302e7df
