name: Package standard

on:
  pull_request:
  push:
    branches: ['*.x']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: standard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standard:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-standard-check.yml@5ed6a6b06b4d8e7c2b2d013eedbe86aeba01d5af
    with:
      standard-ref: 5ed6a6b06b4d8e7c2b2d013eedbe86aeba01d5af
