name: Package standard

on:
  pull_request:
  push:
    branches: ['*.x']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: standard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standard:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-standard-check.yml@5a47fd17171530d4f969a9699d184725b7d32d44
    with:
      standard-ref: 5a47fd17171530d4f969a9699d184725b7d32d44
